Revenues:

<Revenues>:
    orientation: "vertical"
    BoxLayout:
        size_hint_y: None
        height: "20dp"
        BoxLayout:
            size_hint_y: 5
            TextInput:
            	id: money_box
                size_hint_x: 50  # 2
            Button:
                text: "+"
                size_hint_x: 25
            Button:
                text: "-"
                size_hint_x: 25


              #  on_press: root.search_location()